/*
 * $Source: R:/source/driver/raid/RCS\\data.c,v $
 * $Revision: 2.4 $
 * $Date: 2001/07/22 00:30:10 $
 * $Locker:  $
 *
 *	Declares all data used in this driver.  This should be
 *	done in a seperate source file to have greater control
 *	on segment/data allocation.
 *
 * History:
 * $Log: data.c,v $
 * Revision 2.4  2001/07/22 00:30:10  vitus
 * - added hdBuildHook, another context hook handle
 *
 * Revision 2.3  2001/06/25 00:06:30  vitus
 * - added hdMemHook, context hook handle
 *
 * Revision 2.2  1999/10/01 00:53:29  vitus
 * - BuildParent and UpdateParent adjusted to include new VRDEVHDR fields
 *
 * Revision 2.1  1999/09/18 14:36:54  vitus
 * - added apBDisk[], cBDisk to hald BASEDISKs
 *
 * Revision 1.10  1999/06/19 00:26:48  vitus
 * - mehr statistische Daten
 * - MemPool[] nun in DATA, wir sparen Speicher!
 *
 * Revision 1.9  1999/05/26 00:32:35  vitus
 * - some initialization messages now located here.  They may be usefull for
 *   all modules!
 *
 * Revision 1.8  1999/05/12 01:33:34  vitus
 * - added UpdateParent and vrioUpdate for rewriting configuration sectors
 *
 * Revision 1.7  1999/04/21 00:26:04  vitus
 * - added BuildParent and vrioBuild for build processes
 *
 * Revision 1.6  1999/01/22 02:50:35  vitus
 * - aBuildProcess[], cBuildProcess to manyge build processed
 * - cBeeps added: as long as this variable is !0, the driver should be or
 *   flash or do anything usable to notify the sysop
 *
 * Revision 1.5  1998/12/21 23:58:44  vitus
 * - added 'uRegLevel', used instead of flag inside 'fDriverFlags'
 *
 * Revision 1.4  1998/09/08 00:52:47  vitus
 * - added ulADDMaxTransfer (minimum of all ADDs)
 *
 * Revision 1.3  1998/06/26 22:09:30  vitus
 * - corrected apPDev[]
 * - history at top of file
 *
 * Revision 1.2  1998/05/29 01:36:01  vitus
 * - added uDebugLevel
 * - corrected ppMemPool to ppWorkMem
 *
 * Revision 1.1  1998/03/10 02:36:04  vitus
 * Initial revision
 * ---------------------------------------------
 * This code is Copyright Vitus Jensen 1997-2001
 */
#if defined(__WATCOMC__)
# pragma off (unreferenced)
#endif
static char const vcid[]="$Id: data.c,v 2.4 2001/07/22 00:30:10 vitus Exp $";
#if defined(__WATCOMC__)
# pragma on (unreferenced)
#endif

#define INCL_INITRP_ONLY
#include "os2intf.h"

#include "vraid.h"
#include "proto.h"
#include "extern.h"



/* **********************************************************************
 * **** Static Data *****************************************************
 ********************************************************************** */

#if defined(DEBUG)
USHORT		uDebugLevel = 0x8031;
#endif

ULONG		ppDiskDDHeader = 0;
ULONG		ppWorkMem = 0;

PFN		Device_Help =	0;
struct InfoSegGDT FAR	*pGlobalInfoSeg = 0;

USHORT		fDriverFlags =	0;
USHORT		uRegLevel =	0;
USHORT		hdThisDriver =	0;
ULONG		hdMemHook = 0;
ULONG		hdBuildHook = 0;


/* A structure for every unit allocated by our filter.  Used to
 * pass I/Os directly to underlying ADD. */

PBASEDISK	apBDisk[MAX_PDEV] = {0};
USHORT		cBDisk =	0;		/* entries in above table */


/* A structure for every PHYSDEV build for units allocated
 * by our filter.  Enter pointer here. */

PVRDEVHDR	apPDev[MAX_PDEV] = {0};
USHORT		cPDev =		0;		/* entries in above table */


/* A structure for every HOSTDEVICE known as a unit
 * for OS/2.  Enter pointer here. */

PHOSTDRIVE	apHDrv[MAX_HDRV] = {0};
USHORT		cHDrv =		0;		/* entries in above table */


/* A structure for every VRDEVICE requiring the build process. */

BUILDPROCESS	aBuildProcess[MAX_PDEV/2] = {0};
USHORT		cBuildProcess = 0;		/* entries in above table */


/* Dummy VRDEVICEs and VRIOs related to build processes and
 * automatic configuration changes. */

VRDEVHDR	BuildParent = {{0,0,0,0,0,0},0,0,0,0,BuildNotify,0};
VRIO		vrioBuild = {&BuildParent,0,0,0,0,0};
VRDEVHDR	UpdateParent = {{0,0,0,0,0,0},0,0,0,0,UpdateNotify,0};
VRIO		vrioUpdate = {&UpdateParent,0,0,0,0,0};


USHORT		cBeeps = 0;			/* how many reasons for beeping? */




/* Data from underlying ADDs and UNITs. */

USHORT		uADDMaxSGList = 16;		/* see AllocateIorb()! */
ULONG		ulADDMaxTransfer = 16*1024;	/* ??? */
USHORT		uMaxQueueCount = MAX_ACTIVE_IORB; /* reduced if neccessary */
USHORT		fADDFlags = 0;


ULONG		ulTimer = 0;			/* free running 1s timer */


/* Statistical Data: */

USHORT		cIorbInQueue = 0;
USHORT		cVrioInQueue = 0;
USHORT		cIorbAllocated = 0;
USHORT		cVrioAllocated = 0;


/* Message generated by this driver.  May
 * be discarded after INIT. */

#define MSG_REPLACEMENT_STRING	1178		/* %1 %2 %3 ... */

UCHAR	szMsgBuffer[1024]		= {0};

MSGTABLE msgBuffer = {
    MSG_REPLACEMENT_STRING, 1, (PBYTE)szMsgBuffer 
};



/* **********************************************************************
 * **** Initialization Data *********************************************
 ********************************************************************** */

UCHAR	MemPool[30*1024] = {0};
NPUCHAR	npInitData =		MemPool;
BYTE    DeviceTable[MAX_DEVICETABLE_SIZE] = {0};



char _ininit	szMallocFailed[]=	"%s: internal memory allocation failed";
char _ininit	szReadError[]=		"%s: error %04x reading configuration data";
