@ECHO OFF
ECHO Setting up ICAT Source/Binary Environment
SET CAT_MACHINE=COM2:115200
SET CAT_SETUP_RATE=9600
SET CAT_HOST_BIN_PATH=r:\source\driver\raid
SET CAT_COMMUNICATION_TYPE=ASYNC_SIGBRK
SET CAT_HOST_SOURCE_PATH=r:\source\driver\raid
SET CAT_PATH_RECURSE=
SET CAT_MODULE_LIST=vraidd.flt vraid.flt
SET CAT_RESUME=
SET CAT_KDB_INIT=
SET CAT_KEEP_KDB_ON_DETACH=ON
SET CATTAB=8
ECHO Starting ICAT...
icatgam
